name             "cookbook"
maintainer       "Tito Miguel Costa"
maintainer_email "tito@sportlobster.com"
license          "All rights reserved"
description      "Installs/Configures cookbook"
long_description "Installs/Configures cookbook"
version          "0.1.0"

depends "apt"
depends "build-essential"