Zorbus\ApiBundle\Entity\Blog:
    type: entity
    repositoryClass: Zorbus\ApiBundle\Entity\BlogRepository
    table: blog
    gedmo:
        uploadable:
            allowOverwrite: true
            appendNumber: true
            path: '/blog'
            pathMethod: getPhotoPath
            filenameGenerator: SHA1
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
        slug:
            type: string
            length: 255
            gedmo:
                slug:
                    unique: true
                    separator: '-'
                    style: default
                    fields:
                        - title
        content:
            type: text
        points:
            type: integer
            options:
                default: 0
            nullable: true
        photoPath:
            type: string
            nullable: true
            gedmo:
                - uploadableFilePath
        photoName:
            type: string
            nullable: true
            gedmo:
                - uploadableFileName
        photoMimeType:
            type: string
            nullable: true
            gedmo:
                - uploadableFileMimeType
        photoSize:
            type: decimal
            nullable: true
            gedmo:
                - uploadableFileSize
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update