parameters:
    database_name: sportlobster_api_test
    sportlobster.api.memcached.class: Sportlobster\ApiBundle\Mock\Memcached
    
imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
