sportlobster_api:
    resource: "@SportlobsterApiBundle/Controller/"
    type:     annotation
    prefix:   /
    defaults:
        _format: json

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
    defaults:
        _format: html

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
    defaults:
        _format: html

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
    defaults:
        _format: html