sportlobster_api:
    resource: "@SportlobsterApiBundle/Controller/"
    type:     annotation
    prefix:   /
    defaults:
        _format: json

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc