security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern: ^/oauth/v2/token
            security: false

        oauth_client:
            pattern: ^/oauth/client
            security: false

        oauth_authorize:
            pattern: ^/oauth/v2/auth
            anonymous: false
            provider: fos_userbundle
            http_basic:
                realm: "Secured Demo Area"

        api:
            pattern: ^/api
            fos_oauth: true
            stateless: true
            anonymous: false
        
    access_control:
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
