zorbus_linkedin_authorize:
    path:     /authorize
    defaults: { _controller: ZorbusLinkedInBundle:LinkedIn:authorize }

zorbus_linkedin_authenticate:
    path:     /authenticate
    defaults: { _controller: ZorbusLinkedInBundle:LinkedIn:authenticate }