zorbus_linkedin.authorize:
    path:     /authorize
    defaults: { _controller: ZorbusLinkedInBundle:LinkedIn:authorize }

zorbus_linkedin.authenticate:
    path:     /authenticate
    defaults: { _controller: ZorbusLinkedInBundle:LinkedIn:authenticate }