parameters:
    zorbus_linkedin.key: ~
    zorbus_linkedin.secret: ~
    zorbus_linkedin.scope: []

services:
    zorbus_linkedin.guzzle.client:
        class: GuzzleHttp\Client
    zorbus_linkedin.client:
        class: Zorbus\LinkedIn\Client\GuzzleClientAdapter
        arguments:
            - @zorbus_linkedin.guzzle.client
    zorbus_linkedin.storage:
        class: Zorbus\LinkedInBundle\Storage\EntityManagerStorage
        arguments:
            - @doctrine.orm.entity_manager
    zorbus_linkedin.serializer:
        class: Zorbus\LinkedIn\Serializer\JmsSerializer
        arguments:
            - @jms_serializer.serializer
    zorbus_linkedin.manager:
        class: Zorbus\LinkedIn\Manager
        arguments:
            - @zorbus_linkedin.client
            - @zorbus_linkedin.storage
            - @zorbus_linkedin.serializer
    zorbus.api.linkedin.access_token:
         class: Zorbus\ApiBundle\EventListener\LinkedInAccessTokenSubscriber
         arguments:
            - @zorbus_linkedin.storage