Sportlobster\ApiBundle\Entity\OAuthAccessToken:
    type: entity
    table: oauth_access_token
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    manyToOne:
        client:
            targetEntity: OAuthClient
            joinColumn:
                name: client_id
                referencedColumnName: id
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id