Sportlobster\ApiBundle\Entity\User:
    type: entity
    repositoryClass: Sportlobster\ApiBundle\Entity\UserRepository
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 100
            unique: true